### ISSUE TITLE
Upgrade to null safety

### ISSUE THREAD

**Issue by nakuzm** [biocarl/drawing_animation#16]
Because flutter_svg >=0.21.0-nullsafety.0 depends on xml ^5.0.0 and drawing_animation 0.1.4 depends on xml ^4.1.0, flutter_svg >=0.21.0-nullsafety.0 is incompatible with drawing_animation 0.1.4.

**Comment by haucky** [comment]
#19 Done 👍

**Comment by nakuzm** [comment]
drawing_animation doesn't support null safety.

https://dart.dev/null-safety/migration-guide#check-dependency-status
Using this command:
dart pub outdated --mode=null-safety

` dart pub outdated --mode=null-safety             
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name       Current  Upgradable  Resolvable  Latest  

direct dependencies:
drawing_animation  ✗0.1.5   ✗0.1.5      ✗0.1.5      ✗0.1.5  `
