### ISSUE TITLE
Add null safety support

### ISSUE THREAD

**Issue by nakuzm** [biocarl/drawing_animation#20]
https://dart.dev/null-safety/migration-guide#check-dependency-status

dart pub outdated --mode=null-safety
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name Current Upgradable Resolvable Latest

direct dependencies:
drawing_animation ✗0.1.5 ✗0.1.5 ✗0.1.5 ✗0.1.5

**Comment by abbasghomi** [comment]
Opened a PR for this
https://github.com/biocarl/drawing_animation/pull/22

**Comment by aagarcia** [comment]
who have the new version with null safety. Please public this update to pub.dev

**Comment by haucky** [comment]
closing here #22 is merged
