### ISSUE TITLE
Problem with colors

### ISSUE THREAD

**Issue by vico-aguado** [biocarl/drawing_animation#4]
Hi @biocarl!

I tried the example3 but the page with the color example doesn't seem to be working, the lines painting it black. :(

Thanks!

**Comment by r21meghashyam** [comment]
Same problem here, waiting for a solution.

**Comment by r21meghashyam** [comment]
@vico-aguado , as stated

> # Supported SVG specifications
>Only path elements (<path d="M3m1....">) are supported for now. I'm currently considering to add flutter_svg as dependency for more complete SVG parsing.
Attributes
stroke, only Hex-Color without alpha for now
stroke-width
style, but only the both fields above
No transforms are supported, yet.

If you want to change the color of the stroke lines, add stroke="color-code" and stroke-width="pixels" to path element.

ex:

` <path stroke="#ffffff" stroke-width="5"  fill="#ffffff" d="M473.6,92.43.... " />`

**Comment by tibbiyelininja** [comment]
>  I'm currently considering to add flutter_svg as dependency for more complete SVG parsing.

that would be awesome if you implement it.

**Comment by haucky** [comment]
@vico-aguado @r21meghashyam  Actually there was an issue with the colors, sorry for fixing it only now.

See [Fix] Problem with colors e90ec1153fca4b0482bef0a161e6bc5fc808f3bc
