### ISSUE TITLE
Erase animation for SVGs

### ISSUE THREAD

**Issue by tusharojha** [biocarl/drawing_animation#8]
Hi there
I am using this package and I found it helpful. I liked the way it traces the path and shows the drawing effect. I am facing a problem in doing something similar technically but opposite of this animation i.e. erase animation. I want to show an SVG and then trace the path of SVG to erase it. 
Can you help me with this either by providing resources or implementing it in the same package?

**Comment by haucky** [comment]
Hey @tusharojha,
Glad you find it useful! You can already do this with the package by providing a custom animation controller: just set animation value to 1 and animate to 0. Also have a look into curves and [ReverseAnimation](https://api.flutter.dev/flutter/animation/ReverseAnimation-class.html).

**Comment by tusharojha** [comment]
Thank you for your help!
I'm closing this issue now.
